import type { Metadata } from 'next'
import type React from 'react'
import { Barlow } from 'next/font/google'
import { Providers } from './providers'
import Header from '@/app/components/base/Header'
import './styles/globals.scss'

const barlow = Barlow({
  weight: '500',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${barlow.className}`}>
        <Providers>
          <Header></Header>
          <div className="flex relative">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
